<?php

namespace AdherentBundle\Repository;

/**
 * DdeEpargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdeEpargeRepository extends \Doctrine\ORM\EntityRepository
{
}
