<?php

namespace AdherentBundle\Repository;

/**
 * DdeReeditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdeReeditionRepository extends \Doctrine\ORM\EntityRepository
{
}
