<?php

namespace AdherentBundle\Repository;

/**
 * DdeRechargementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdeRechargementRepository extends \Doctrine\ORM\EntityRepository
{
}
