<?php

namespace AdherentBundle\Repository;

/**
 * DdeSouscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdeSouscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
