<?php

namespace AdherentBundle\Repository;

/**
 * DdeVirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdeVirementRepository extends \Doctrine\ORM\EntityRepository
{
}
