<?php

namespace AdherentBundle\Repository;

/**
 * RegularisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegularisationRepository extends \Doctrine\ORM\EntityRepository
{
}
