<?php

namespace AuthenticateBundle\Repository;

/**
 * FindPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FindPasswordRepository extends \Doctrine\ORM\EntityRepository
{
}
